const path=require('path');const fs=require('fs');const express=require('express');const cookieParser=require('cookie-parser');const bcrypt=require('bcryptjs');const jwt=require('jsonwebtoken');const Database=require('better-sqlite3');const multer=require('multer');
const PORT=Number(process.env.PORT||3000),JWT_SECRET=process.env.JWT_SECRET||'CHANGE_THIS_IN_PRODUCTION',ADMIN_EMAIL=process.env.ADMIN_EMAIL||'admin@example.com',ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'ChangeMe123!';
const dataDir=path.join(__dirname,'data'),uploadDir=path.join(__dirname,'public','uploads');fs.mkdirSync(dataDir,{recursive:true});fs.mkdirSync(uploadDir,{recursive:true});const db=new Database(path.join(dataDir,'nightbyte.db'));db.pragma('journal_mode=WAL');
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,email TEXT UNIQUE NOT NULL,password_hash TEXT NOT NULL,role TEXT NOT NULL DEFAULT 'user',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS games(id INTEGER PRIMARY KEY AUTOINCREMENT,slug TEXT UNIQUE NOT NULL,title TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',category TEXT NOT NULL DEFAULT 'Arcade',thumbnail TEXT NOT NULL DEFAULT '',game_url TEXT NOT NULL DEFAULT '',plays INTEGER NOT NULL DEFAULT 0,likes INTEGER NOT NULL DEFAULT 0,published INTEGER NOT NULL DEFAULT 1,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);CREATE TABLE IF NOT EXISTS favorites(user_id INTEGER NOT NULL,game_id INTEGER NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(user_id,game_id));CREATE TABLE IF NOT EXISTS ratings(user_id INTEGER NOT NULL,game_id INTEGER NOT NULL,rating INTEGER NOT NULL CHECK(rating BETWEEN 1 AND 5),created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(user_id,game_id));CREATE TABLE IF NOT EXISTS play_events(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,game_id INTEGER NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP);`);
const seed=[['neon-dash','Neon Dash','Dodge falling blocks and chase a high score.','Arcade','dodge'],['block-drop','Block Drop','Stack a simple set of falling shapes.','Puzzle','blocks'],['star-hop','Star Hop','Bounce through a tiny endless arcade challenge.','Arcade','hop'],['pixel-garden','Pixel Garden','A relaxing pixel-themed demo.','Casual','garden'],['orbital','Orbital','Keep your orbit alive and score points.','Skill','orb'],['color-flip','Color Flip','A quick color matching puzzle.','Puzzle','flip'],['tiny-racer','Tiny Racer','A compact racing-themed arcade demo.','Racing','race'],['sky-catch','Sky Catch','Catch falling objects in the sky.','Arcade','catch'],['maze-light','Maze Light','Navigate a minimalist maze.','Puzzle','maze'],['shape-stack','Shape Stack','Stack shapes without losing balance.','Skill','stack']];const ins=db.prepare(`INSERT OR IGNORE INTO games(slug,title,description,category,game_url) VALUES(?,?,?,?,?)`);for(const g of seed)ins.run(...g);
if(!db.prepare('SELECT id FROM users WHERE email=?').get(ADMIN_EMAIL)){db.prepare('INSERT INTO users(email,password_hash,role) VALUES(?,?,?)').run(ADMIN_EMAIL,bcrypt.hashSync(ADMIN_PASSWORD,12),'admin')}
const app=express();app.use(express.json({limit:'2mb'}));app.use(cookieParser());app.use(express.static(path.join(__dirname,'public')));
const upload=multer({storage:multer.diskStorage({destination:uploadDir,filename:(req,file,cb)=>{const ext=path.extname(file.originalname).toLowerCase().slice(0,10);cb(null,Date.now()+'-'+Math.random().toString(36).slice(2)+ext)}}),limits:{fileSize:3*1024*1024},fileFilter:(req,file,cb)=>cb(null,/^image\/(png|jpe?g|webp|gif)$/.test(file.mimetype))});
function auth(req,res,next){try{const t=req.cookies.nb_session;if(!t)throw 0;const p=jwt.verify(t,JWT_SECRET),u=db.prepare('SELECT id,email,role,created_at FROM users WHERE id=?').get(p.id);if(!u)throw 0;req.user=u;next()}catch(e){res.status(401).json({error:'Sign in required'})}}
function admin(req,res,next){auth(req,res,()=>req.user.role==='admin'?next():res.status(403).json({error:'Admin access required'}))}
function issue(user,res){const t=jwt.sign({id:user.id},JWT_SECRET,{expiresIn:'7d'});res.cookie('nb_session',t,{httpOnly:true,sameSite:'lax',secure:process.env.NODE_ENV==='production',maxAge:7*86400000});}
function gameRow(id){return db.prepare(`SELECT g.*,ROUND(COALESCE(AVG(r.rating),0),1) rating,COUNT(r.rating) rating_count FROM games g LEFT JOIN ratings r ON r.game_id=g.id WHERE g.id=? GROUP BY g.id`).get(id)}
app.get('/api/health',(req,res)=>res.json({ok:true,version:'3.0.0',database:'sqlite'}));
app.get('/api/games',(req,res)=>{const q=String(req.query.q||'').trim(),cat=String(req.query.category||'').trim(),sort=String(req.query.sort||'popular');let order=sort==='new'?'g.id DESC':sort==='likes'?'g.likes DESC':'g.plays DESC';let sql=`SELECT g.*,ROUND(COALESCE(AVG(r.rating),0),1) rating,COUNT(r.rating) rating_count FROM games g LEFT JOIN ratings r ON r.game_id=g.id WHERE g.published=1`;const vals=[];if(q){sql+=' AND (LOWER(g.title) LIKE ? OR LOWER(g.description) LIKE ? OR LOWER(g.category) LIKE ?)';const z='%'+q.toLowerCase()+'%';vals.push(z,z,z)}if(cat){sql+=' AND g.category=?';vals.push(cat)}sql+=` GROUP BY g.id ORDER BY ${order},g.id DESC`;res.json({games:db.prepare(sql).all(...vals)});});
app.get('/api/games/:id',(req,res)=>{const g=gameRow(req.params.id);if(!g||!g.published)return res.status(404).json({error:'Game not found'});res.json({game:g})});
app.post('/api/auth/register',(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||'');if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(email)||password.length<8)return res.status(400).json({error:'Use a valid email and an 8+ character password'});try{const id=db.prepare('INSERT INTO users(email,password_hash) VALUES(?,?)').run(email,bcrypt.hashSync(password,12)).lastInsertRowid;const u=db.prepare('SELECT id,email,role,created_at FROM users WHERE id=?').get(id);issue(u,res);res.json({ok:true,user:u})}catch(e){res.status(409).json({error:'Account already exists'})}});
app.post('/api/auth/login',(req,res)=>{const email=String(req.body.email||'').trim().toLowerCase(),password=String(req.body.password||''),u=db.prepare('SELECT * FROM users WHERE email=?').get(email);if(!u||!bcrypt.compareSync(password,u.password_hash))return res.status(401).json({error:'Invalid email or password'});issue(u,res);res.json({ok:true,user:{id:u.id,email:u.email,role:u.role,created_at:u.created_at}})});
app.post('/api/auth/logout',(req,res)=>{res.clearCookie('nb_session');res.json({ok:true})});app.get('/api/auth/me',auth,(req,res)=>res.json({user:req.user}));
app.post('/api/games/:id/play',(req,res)=>{const g=db.prepare('SELECT id FROM games WHERE id=? AND published=1').get(req.params.id);if(!g)return res.status(404).json({error:'Game not found'});let uid=null;try{uid=jwt.verify(req.cookies.nb_session,JWT_SECRET).id}catch{}db.transaction(()=>{db.prepare('INSERT INTO play_events(user_id,game_id) VALUES(?,?)').run(uid,g.id);db.prepare('UPDATE games SET plays=plays+1 WHERE id=?').run(g.id)})();res.json({ok:true})});
app.post('/api/games/:id/favorite',auth,(req,res)=>{const exists=db.prepare('SELECT 1 FROM favorites WHERE user_id=? AND game_id=?').get(req.user.id,req.params.id);if(exists)db.prepare('DELETE FROM favorites WHERE user_id=? AND game_id=?').run(req.user.id,req.params.id);else db.prepare('INSERT INTO favorites(user_id,game_id) VALUES(?,?)').run(req.user.id,req.params.id);res.json({favorited:!exists})});
app.get('/api/me/favorites',auth,(req,res)=>res.json({games:db.prepare('SELECT g.* FROM games g JOIN favorites f ON f.game_id=g.id WHERE f.user_id=? ORDER BY f.created_at DESC').all(req.user.id)}));
app.get('/api/games/:id/my-rating',auth,(req,res)=>res.json({rating:db.prepare('SELECT rating FROM ratings WHERE user_id=? AND game_id=?').get(req.user.id,req.params.id)?.rating||0}));
app.post('/api/games/:id/rating',auth,(req,res)=>{const rating=Number(req.body.rating);if(!Number.isInteger(rating)||rating<1||rating>5)return res.status(400).json({error:'Rating must be 1-5'});db.prepare(`INSERT INTO ratings(user_id,game_id,rating) VALUES(?,?,?) ON CONFLICT(user_id,game_id) DO UPDATE SET rating=excluded.rating`).run(req.user.id,req.params.id,rating);res.json({ok:true,rating})});
app.get('/api/admin/stats',admin,(req,res)=>{res.json({users:db.prepare('SELECT COUNT(*) n FROM users').get().n,games:db.prepare('SELECT COUNT(*) n FROM games').get().n,published:db.prepare('SELECT COUNT(*) n FROM games WHERE published=1').get().n,plays:db.prepare('SELECT COALESCE(SUM(plays),0) n FROM games').get().n,ratings:db.prepare('SELECT COUNT(*) n FROM ratings').get().n})});
app.get('/api/admin/games',admin,(req,res)=>res.json({games:db.prepare('SELECT * FROM games ORDER BY id DESC').all()}));
app.post('/api/admin/games',admin,(req,res)=>{const b=req.body||{};if(!b.slug||!b.title)return res.status(400).json({error:'slug and title are required'});try{const id=db.prepare('INSERT INTO games(slug,title,description,category,thumbnail,game_url,published) VALUES(?,?,?,?,?,?,?)').run(b.slug,b.title,b.description||'',b.category||'Arcade',b.thumbnail||'',b.game_url||'',b.published===false?0:1).lastInsertRowid;res.json({game:gameRow(id)})}catch(e){res.status(409).json({error:'Slug already exists'})}});
app.patch('/api/admin/games/:id',admin,(req,res)=>{const allowed=['title','description','category','thumbnail','game_url','published','slug'];const entries=Object.entries(req.body||{}).filter(([k])=>allowed.includes(k));if(!entries.length)return res.status(400).json({error:'No editable fields supplied'});const sets=entries.map(([k])=>`${k}=?`).join(',');db.prepare(`UPDATE games SET ${sets} WHERE id=?`).run(...entries.map(([,v])=>v),req.params.id);res.json({game:gameRow(req.params.id)})});
app.delete('/api/admin/games/:id',admin,(req,res)=>{db.prepare('DELETE FROM games WHERE id=?').run(req.params.id);res.json({ok:true})});
app.post('/api/admin/games/:id/thumbnail',admin,upload.single('thumbnail'),(req,res)=>{if(!req.file)return res.status(400).json({error:'Image required (PNG/JPG/WEBP/GIF, max 3MB)'});const url='/uploads/'+req.file.filename;db.prepare('UPDATE games SET thumbnail=? WHERE id=?').run(url,req.params.id);res.json({thumbnail:url})});
app.get('/api/admin/users',admin,(req,res)=>res.json({users:db.prepare('SELECT id,email,role,created_at FROM users ORDER BY id DESC').all()}));
app.get('/api/admin/play-events',admin,(req,res)=>res.json({events:db.prepare(`SELECT p.id,p.created_at,g.title,u.email FROM play_events p JOIN games g ON g.id=p.game_id LEFT JOIN users u ON u.id=p.user_id ORDER BY p.id DESC LIMIT 100`).all()}));
app.get('/api/categories',(req,res)=>res.json({categories:db.prepare('SELECT DISTINCT category FROM games WHERE published=1 ORDER BY category').all().map(x=>x.category)}));
app.get('/{*splat}',(req,res)=>res.sendFile(path.join(__dirname,'public','index.html')));app.listen(PORT,()=>console.log(`Nightbyte V3 on http://localhost:${PORT}`));
